```
#!/bin/sh
set -x
#Adding IP Information 

echo  "auto lo
iface lo inet loopback
auto eth0
iface eth0 inet static
        address 192.168.1.100
        netmask 255.255.255.0
        gateway 192.168.1.1
        network 192.168.1.0
        broadcast 192.168.1.255
        dsn-nameservers 192.168.1.1 8.8.8.8"  > /etc/network/interfaces

#Change the Hostname

echo "system100" > /etc/hostname
hostname -F /etc/hostname

#After that Change the Host name to system xx to system xx in

echo "# Set the host name here to resolv the Hostname 
127.0.0.1	localhost
192.168.1.100	system81" > /etc/hosts


#Set the Resolv.conf
 
echo "# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

nameserver 192.168.1.1
nameserver 8.8.8.8" > /etc/resolv.conf

#set the Resolv.conf Base file 


echo "# Here if we set the Resolv then it wont rewrite the DNS names repeatly after a Reboot

nameserver 192.168.1.1
nameserver 8.8.8.8" > /etc/resolvconf/resolv.conf.d/base


# Restart the Network to take effect before other actions 


sudo /etc/init.d/networking restart


#Update the Repository


sudo apt-get update


# Install Cinnamon in Ubuntu

sudo add-apt-repository ppa:tsvetko.tsvetkov/cinnamon -y

sudo apt-get update

sudo apt-get install cinnamon -y


# Install the Software Properties Wiht Phython


sudo apt-get install python-software-properties -y

wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -

Setup repository with:

sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'

sudo apt-get update

sudo apt-get install google-chrome-stable -y

# Installing Java Manually 


sudo mkdir -p /usr/lib/jvm

wget ftp://192.168.1.15/arrivu_contents/jdk-8-linux-x64.tar.gz

sudo mv jdk-8-linux-x64.tar.gz /usr/lib/jvm

cd /usr/lib/jvm

sudo tar -zxvf jdk-8-linux-x64.tar.gz

sudo rm jdk-8-linux-x64.tar.gz

ls -l

sudo update-alternatives --install "/usr/bin/javac" "javac" "/usr/lib/jvm/jdk1.8.0/bin/javac" 1

sudo update-alternatives --install "/usr/bin/java" "java" "/usr/lib/jvm/jdk1.8.0/bin/java" 1

sudo update-alternatives --set "javac" "/usr/lib/jvm/jdk1.8.0/bin/javac"

sudo update-alternatives --set "java" "/usr/lib/jvm/jdk1.8.0/bin/java"


# Add the following entries to the bottom of your /etc/profile file:

echo "JAVA_HOME=/usr/lib/jvm/jdk1.8.0 PATH=$PATH:$JAVA_HOME/bin export JAVA_HOME export PATH" > /etc/profile

. /etc/profile

java -version


# Install the Advanced vi Editor 

sudo apt-get install vim -y

cd ~

# Installing liberoffice

sudo add-apt-repository ppa:libreoffice/libreoffice-4-2 -y

sudo apt-get update && sudo apt-get install libreoffice -y

# Installing Sublime test

sudo add-apt-repository ppa:webupd8team/sublime-text-3 -y

sudo apt-get update && sudo apt-get install sublime-text

# Installing git

sudo add-apt-repository ppa:git-core/ppa -y

sudo apt-get update && sudo apt-get -y install git git-man git-svn

# Installing Ruby

sudo apt-add-repository ppa:brightbox/ruby-ng -y

sudo apt-get update && sudo apt-get install ruby1.9.3 -y

# Install the Byobu Terminal 


sudo apt-get install byobu -y


# Install the htop 


sudo apt-get install htop -y

# Install Pidgin Messenger 

sudo apt-get install pidgin* -y


# Install the Sprak Messenger 

sudo apt-get install ia32-libs -y

wget ftp://192.168.1.15/arrivu_contents/spark_2_6_3.tar.gz

sudo tar -zxvf spark_2_6_3.tar.gz

sudo mkdir /opt/spark

sudo mv Spark/* /opt/spark/


sudo echo "[Desktop Entry]
Name=Spark
Version=2.6.3
GenericName=Spark
X-GNOME-FullName=Spark
Comment=ignite realtime Spark IM client
Type=Application
Categories=Application;Utility;
Path=/opt/spark
Exec=/bin/bash Spark
Terminal=false
StartupNotify=true
Icon=/opt/spark/spark.png
TargetEnvironment=Unity" > /usr/share/applications/spark.desktop


cd /opt/spark

wget https://dl.dropbox.com/u/50880014/spark.png

./Spark &

# Install and Configure Samba Share While every boot 

sudo apt-get install smbfs -y

echo "username=sysadmin
password=admin123$" > /home/sysadmin/.smbcredentials

chmod 0600 /home/sysadmin/.smbcredentials

mkdir -p /home/sysadmin/samba

chown sysadmin:sysadmin /home/sysadmin/samba

echo "//192.168.1.15/sysadmin /home/sysadmin/samba cifs credentials=/home/sysadmin/.smbcredentials,uid=sysadmin,gid=sysadmin 0 0" >> /etc/fstab

mount -a

echo "Installtion Completed"

exit
```
